# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-0bf0xH-gdsgpV1dVPTZOsilqAAbKEQ
"""

from flask import Flask, jsonify
app = Flask(__name__)

@app.route('/',methods=['GET'])
def hello_world():
  json_response ={
      'status_code' :200,
      'description' : "Menyapa Hello World",
      'data': "Hello World"
  }

  response_data = jsonify(json_response)
  return response_data

if  __name__ == '__main__':
  app.run()